FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

ENV PORT=8080
ENV GUNICORN_CMD_ARGS="--workers 3 --threads 1 --timeout 900"

CMD exec gunicorn --bind 0.0.0.0:$PORT $GUNICORN_CMD_ARGS app:app
